创建目录 D:/AppServ/www/cms/runtime/ 成功.
创建文件 D:/AppServ/www/cms/config.inc.php 成功.
创建目录 D:/AppServ/www/cms/classes/ 成功.
创建目录 D:/AppServ/www/cms/commons/ 成功.
创建目录 D:/AppServ/www/cms/public 成功.
创建目录 D:/AppServ/www/cms/public/uploads/ 成功.
创建目录 D:/AppServ/www/cms/public/css/ 成功.
创建目录 D:/AppServ/www/cms/public/js/ 成功.
创建目录 D:/AppServ/www/cms/public/images/ 成功.
创建目录 ./admin/ 成功.
创建目录 ./admin/models/ 成功.
创建目录 ./admin/controls/ 成功.
创建目录 ./admin/views/ 成功.
创建目录 ./admin/views/default 成功.
创建目录 ./admin/views/default/public/ 成功.
创建目录 ./admin/views/default/resource/ 成功.
创建目录 ./admin/views/default/resource/css/ 成功.
创建目录 ./admin/views/default/resource/js/ 成功.
创建目录 ./admin/views/default/resource/images/ 成功.
创建文件 D:/AppServ/www/cms/commons/functions.inc.php 成功.
创建文件 ./admin/controls/common.class.php 成功.
创建文件 ./admin/controls/index.class.php 成功.